from pathlib import Path

# 1) Add team abbreviation/id aliases from current + prior schedules into ctx.
p=Path('free_data_v16.py');s=p.read_text()
load_anchor="""    prev_team_box=grab('team_box','team_box',int(year)-1)\n"""
if "prev_schedule=grab('schedules','cfb_schedule',int(year)-1)" not in s:
    s=s.replace(load_anchor,load_anchor+"    prev_schedule=grab('schedules','cfb_schedule',int(year)-1)\n",1)
anchor='''    ctx=base._team_context(schedule,adv,pidx,resolved_week)\n\n    cur_team=_team_baselines(team_box,resolved_week)'''
insert='''    ctx=base._team_context(schedule,adv,pidx,resolved_week)\n\n    # Build NFL-style canonical team aliases from current + prior schedules. The\n    # previous season is useful before the next-day schedule file catches up, and\n    # gives stable ESPN IDs for logos without any paid API.\n    alias_schedules=[x for x in [schedule,prev_schedule] if x is not None and not x.empty]\n    for sched in alias_schedules:\n        hname=base._col(sched,'home_team','home_display_name','home_team_name','home_name')\n        aname=base._col(sched,'away_team','away_display_name','away_team_name','away_name')\n        habbr=base._col(sched,'home_abbreviation','home_abbr','home_team_abbreviation')\n        aabbr=base._col(sched,'away_abbreviation','away_abbr','away_team_abbreviation')\n        hid=base._col(sched,'home_team_id','home_id','home_espn_id')\n        aid=base._col(sched,'away_team_id','away_id','away_espn_id')\n        for _,rr in sched.iterrows():\n            for nc,ac,ic in [(hname,habbr,hid),(aname,aabbr,aid)]:\n                name=str(rr.get(nc) or '').strip() if nc else ''\n                abbr=str(rr.get(ac) or '').strip() if ac else ''\n                eid=str(rr.get(ic) or '').strip() if ic else ''\n                if not name:continue\n                d=ctx.setdefault(name,{'sp':0,'srs':0,'core':0,'elo':1500,'talent':0,'off_rating':0,'def_rating':0,'pace':0,'off_expl':0,'def_expl':0,'def_passing':0,'def_rushing':0,'havoc':0})\n                d['canonical_name']=name\n                if abbr:d['abbreviation']=abbr\n                if eid and eid.lower()!='nan':\n                    d['espn_id']=eid\n                    d['logo']=d.get('logo') or f'https://a.espncdn.com/i/teamlogos/ncaa/500/{eid}.png'\n                if abbr:\n                    alias=dict(d);alias['canonical_name']=name;ctx[abbr]=alias\n\n    cur_team=_team_baselines(team_box,resolved_week)'''
if anchor in s:s=s.replace(anchor,insert,1)
p.write_text(s)

# 2) Add prop-derived game synthesis to runtime. This is the final fallback when a
# free schedule endpoint has not published the next day but Underdog already has lines.
p=Path('cfb_runtime_v20.py');s=p.read_text()
if 'def games_from_props(' not in s:
    marker='''\ndef _branding_from_games(games:Iterable[dict])->Dict[str,dict]:\n'''
    fn='''\ndef games_from_props(rows:List[dict],ctx:Dict[str,dict])->List[dict]:\n    out={}\n    def resolve(code):\n        code=str(code or '')\n        d=ctx.get(code,{}) or {}\n        return str(d.get('canonical_name') or d.get('display_name') or code),d\n    for r in rows or []:\n        away=str(r.get('away') or '').strip();home=str(r.get('home') or '').strip()\n        if not away or not home:\n            m=str(r.get('matchup') or '')\n            parts=re.split(r'\\s+@\\s+',m,maxsplit=1)\n            if len(parts)==2:away=away or parts[0].strip();home=home or parts[1].strip()\n        if not away or not home:continue\n        an,ad=resolve(away);hn,hd=resolve(home)\n        dt=r.get('scheduled_at') or r.get('start_date')\n        key=(_norm(an),_norm(hn),str(dt or ''))\n        out[key]={'id':str(r.get('event_id') or ''),'week':None,'away_team':an,'home_team':hn,'away_abbreviation':away,'home_abbreviation':home,'away_espn_id':str(ad.get('espn_id') or ''),'home_espn_id':str(hd.get('espn_id') or ''),'away_logo':ad.get('logo') or '','home_logo':hd.get('logo') or '','start_date':dt,'scheduled_at':dt,'neutral_site':False,'source':'Underdog live slate'}\n    return list(out.values())\n\n'''
    if marker not in s:raise SystemExit('runtime insertion marker missing')
    s=s.replace(marker,fn+marker,1)
p.write_text(s)

# 3) Finish app: import prop game synthesis and bootstrap tomorrow's event board from
# the already-live Underdog feed when the schedule file/scoreboard returns no games.
p=Path('app.py');s=p.read_text()
s=s.replace('local_now, scope_target_date, logo_coverage, day_games, canonical_prop_team, prop_rows_date_label)',
            'local_now, scope_target_date, logo_coverage, day_games, canonical_prop_team, prop_rows_date_label, games_from_props)')
needle='''    week_games=annotate_games(week_games)\n    display_games=filter_games_by_scope(week_games,slate_scope,pt_now)\nctx=ensure_branding(ctx,week_games,players)\n'''
replacement='''    week_games=annotate_games(week_games)\n    display_games=filter_games_by_scope(week_games,slate_scope,pt_now)\n# Final NFL-style fallback: if the official/free schedule is behind but the live book\n# has tomorrow's CFB board open, build the event slate from those live event records.\nif slate_scope in {"Today","Tomorrow"} and not display_games:\n    try:\n        boot_rows,boot_debug=fetch_underdog_cfb_props(force=force)\n        st.session_state["ud_cfb_rows"]=boot_rows\n        st.session_state["ud_cfb_debug"]=boot_debug\n        scoped_boot=filter_props_by_scope(boot_rows,slate_scope,pt_now)\n        raw_prop_games=games_from_props(scoped_boot,ctx)\n        for rg in raw_prop_games:\n            away=rg.get("away_team");home=rg.get("home_team")\n            if not away or not home:continue\n            key=(norm_name(away),norm_name(home));market=market_map.get(key,{})\n            manual_gc=game_weather_context(away,home,game_context_df)\n            pg=project_game(away,home,ctx,market,neutral=bool(manual_gc.get("neutral",False)))\n            pg["weather"]={"wind_mph":sf(manual_gc.get("wind_mph")),"precip_prob":sf(manual_gc.get("precip_prob")),"temp_f":sf(manual_gc.get("temp_f"),70)}\n            pg["game_id"]=rg.get("id");pg["start_date"]=rg.get("start_date")\n            for k in ["away_abbreviation","home_abbreviation","away_espn_id","home_espn_id","away_logo","home_logo"]:pg[k]=rg.get(k) or ""\n            week_games.append(pg)\n        week_games=annotate_games(week_games)\n        display_games=filter_games_by_scope(week_games,slate_scope,pt_now)\n    except Exception as e:\n        bundle.setdefault("errors",{})["live_slate_bootstrap"]=str(e)\nctx=ensure_branding(ctx,week_games,players)\n'''
if needle not in s:raise SystemExit('app bootstrap insertion marker missing')
s=s.replace(needle,replacement,1)
p.write_text(s)
