from pathlib import Path

p=Path('underdog_cfb_v15.py'); s=p.read_text()
old="""def _game_names(g):\n    if not isinstance(g,dict):return '','',''\n    away=str(g.get('away_team') or g.get('away_team_name') or g.get('away') or '').strip(); home=str(g.get('home_team') or g.get('home_team_name') or g.get('home') or '').strip(); title=str(g.get('title') or g.get('matchup') or g.get('name') or '').strip()\n    if (not away or not home) and title:\n        parts=re.split(r'\\s+(?:@|at|vs\\.?|v\\.)\\s+',title,maxsplit=1,flags=re.I)\n        if len(parts)==2:away=away or parts[0].strip();home=home or parts[1].strip()\n    return away,home,f'{away} @ {home}' if away and home else title\n"""
new="""def _game_names(g):\n    if not isinstance(g,dict):return '','',''\n    away=str(g.get('away_team') or g.get('away_team_name') or g.get('away') or '').strip(); home=str(g.get('home_team') or g.get('home_team_name') or g.get('home') or '').strip()\n    full=str(g.get('full_team_names_title') or '').strip()\n    title=str(g.get('title') or g.get('abbreviated_title') or g.get('matchup') or g.get('name') or '').strip()\n    source=full or title\n    if (not away or not home) and source:\n        parts=re.split(r'\\s+(?:@|at|vs\\.?|v\\.)\\s+',source,maxsplit=1,flags=re.I)\n        if len(parts)==2:away=away or parts[0].strip();home=home or parts[1].strip()\n    return away,home,f'{away} @ {home}' if away and home else source\n"""
if old not in s: raise SystemExit('game names marker missing')
s=s.replace(old,new,1)
old="""        tid=app.get('team_id') or p.get('team_id'); t=_team(app,p,teams.get(str(tid),{}) if tid is not None else {})\n        out.append(_line_row(name,t,prop,line,url,game,lo,mid))\n"""
new="""        tid=str(app.get('team_id') or p.get('team_id') or '')\n        ga,gh,_gm=_game_names(game)\n        if tid and tid==str(game.get('away_team_id') or ''): t=ga\n        elif tid and tid==str(game.get('home_team_id') or ''): t=gh\n        else: t=_team(app,p,teams.get(tid,{}) if tid else {})\n        row=_line_row(name,t,prop,line,url,game,lo,mid)\n        row['team_id']=tid\n        row['position']=str(p.get('position_name') or p.get('position_display_name') or '')\n        row['player_image_url']=str(p.get('image_url') or p.get('light_image_url') or '')\n        out.append(row)\n"""
if old not in s: raise SystemExit('native team marker missing')
s=s.replace(old,new,1)
p.write_text(s)

p=Path('app.py'); s=p.read_text()
old="""            # Current-season roster identity overrides the historical sample school.\n            current_team=str(pr.get('current_team') or '')\n            team=''\n            if current_team:\n                for t in [row_game['away'],row_game['home']]:\n                    a,b=norm_name(current_team),norm_name(t)\n                    if a==b or (len(a)>=4 and (a in b or b in a)):\n                        team=t; break\n            if not team: team=canonical_prop_team(r,row_game,pr)\n            opp=row_game[\"home\"] if team==row_game[\"away\"] else row_game[\"away\"]\n            tc=get_team(ctx,team or \"\"); oc=get_team(ctx,opp or \"\")\n            proj,sd,notes=player_projection(pr,r.get(\"prop\"),tc,oc,row_game,team or \"\")\n"""
new="""            # Authoritative current team comes from Underdog player team_id matched\n            # to this game's away_team_id/home_team_id. Historical school stays only\n            # as provenance for the player's production sample.\n            live_team=str(r.get('team') or '')\n            team=canonical_prop_team({**r,'team':live_team},row_game,pr)\n            if team not in {row_game['away'],row_game['home']}:\n                team=''\n                for t in [row_game['away'],row_game['home']]:\n                    a,b=norm_name(live_team),norm_name(t)\n                    if a and (a==b or a in b or b in a): team=t; break\n            opp=row_game[\"home\"] if team==row_game[\"away\"] else row_game[\"away\"]\n            tc=get_team(ctx,team or \"\"); oc=get_team(ctx,opp or \"\")\n            model_pr=dict(pr)\n            if team: model_pr['current_team']=team\n            proj,sd,notes=player_projection(model_pr,r.get(\"prop\"),tc,oc,row_game,team or \"\")\n"""
if old not in s: raise SystemExit('app live-team block marker missing')
s=s.replace(old,new,1)
# Preserve the complete opportunity/advanced calibration, but make it live-team aware.
s=s.replace('src=str(pr.get("sample_source") or "fallback").lower(); gp=sf(pr.get("games"),0)', 'src=str(model_pr.get("sample_source") or "fallback").lower(); gp=sf(model_pr.get("games"),0)',1)
s=s.replace("roster_confirmed=bool(pr.get('current_team')) or src=='current'", "roster_confirmed=bool(model_pr.get('current_team')) or src=='current'",1)
s=s.replace("transferred=bool(pr.get('current_team') and pr.get('team') and norm_name(pr.get('current_team'))!=norm_name(pr.get('team')))", "transferred=bool(model_pr.get('current_team') and model_pr.get('team') and norm_name(model_pr.get('current_team'))!=norm_name(model_pr.get('team')))",1)
s=s.replace("has_adv=any(sf(pr.get(k))>0 for k in ['adv_pass_att','adv_rush_car','adv_targets'])", "has_adv=any(sf(model_pr.get(k))>0 for k in ['adv_pass_att','adv_rush_car','adv_targets'])",1)
s=s.replace('APP_VERSION = "CFB Prop Engine v2.4 — NFL-STYLE COMPLETE OPPORTUNITY + ADVANCED DATA"','APP_VERSION = "CFB Prop Engine v2.4.1 — NFL-STYLE LIVE TEAM + COMPLETE OPPORTUNITY"',1)
p.write_text(s)
print('v2.4.1 live-team patch applied')
