from pathlib import Path

# 1) Underdog already gives the authoritative CURRENT team_id on both the player
# appearance and the game. Resolve it directly to the away/home school name.
p=Path('underdog_cfb_v15.py'); s=p.read_text()
old="""def _game_names(g):\n    if not isinstance(g,dict):return '','',''\n    away=str(g.get('away_team') or g.get('away_team_name') or g.get('away') or '').strip(); home=str(g.get('home_team') or g.get('home_team_name') or g.get('home') or '').strip(); title=str(g.get('title') or g.get('matchup') or g.get('name') or '').strip()\n    if (not away or not home) and title:\n        parts=re.split(r'\\s+(?:@|at|vs\\.?|v\\.)\\s+',title,maxsplit=1,flags=re.I)\n        if len(parts)==2:away=away or parts[0].strip();home=home or parts[1].strip()\n    return away,home,f'{away} @ {home}' if away and home else title\n"""
new="""def _game_names(g):\n    if not isinstance(g,dict):return '','',''\n    away=str(g.get('away_team') or g.get('away_team_name') or g.get('away') or '').strip(); home=str(g.get('home_team') or g.get('home_team_name') or g.get('home') or '').strip()\n    # Native CFB feed exposes full_team_names_title even when away_team/home_team\n    # fields are absent. Prefer full schools so the model/context/logo layer matches.\n    full=str(g.get('full_team_names_title') or '').strip()\n    title=str(g.get('title') or g.get('abbreviated_title') or g.get('matchup') or g.get('name') or '').strip()\n    source=full or title\n    if (not away or not home) and source:\n        parts=re.split(r'\\s+(?:@|at|vs\\.?|v\\.)\\s+',source,maxsplit=1,flags=re.I)\n        if len(parts)==2:away=away or parts[0].strip();home=home or parts[1].strip()\n    return away,home,f'{away} @ {home}' if away and home else source\n"""
if old not in s: raise SystemExit('game names marker missing')
s=s.replace(old,new,1)
old="""        tid=app.get('team_id') or p.get('team_id'); t=_team(app,p,teams.get(str(tid),{}) if tid is not None else {})\n        out.append(_line_row(name,t,prop,line,url,game,lo,mid))\n"""
new="""        tid=str(app.get('team_id') or p.get('team_id') or '')\n        # v6 CFB currently omits a top-level teams collection, but every game has\n        # away_team_id/home_team_id. That is enough to map the player's live team\n        # exactly without relying on stale prior-season roster identity.\n        ga,gh,_gm=_game_names(game)\n        if tid and tid==str(game.get('away_team_id') or ''): t=ga\n        elif tid and tid==str(game.get('home_team_id') or ''): t=gh\n        else: t=_team(app,p,teams.get(tid,{}) if tid else {})\n        row=_line_row(name,t,prop,line,url,game,lo,mid)\n        row['team_id']=tid\n        row['position']=str(p.get('position_name') or p.get('position_display_name') or '')\n        row['player_image_url']=str(p.get('image_url') or p.get('light_image_url') or '')\n        out.append(row)\n"""
if old not in s: raise SystemExit('native team marker missing')
s=s.replace(old,new,1)
p.write_text(s)

# 2) Feed live current team into the opportunity model. Keep the historical school
# only as provenance for the production sample; do not use it as today's role/team.
p=Path('app.py'); s=p.read_text()
old="""            # Current-season roster identity overrides the historical sample school.\n            current_team=str(pr.get('current_team') or '')\n            team=''\n            if current_team:\n                for t in [row_game['away'],row_game['home']]:\n                    a,b=norm_name(current_team),norm_name(t)\n                    if a==b or (len(a)>=4 and (a in b or b in a)):\n                        team=t; break\n            if not team: team=canonical_prop_team(r,row_game,pr)\n            opp=row_game[\"home\"] if team==row_game[\"away\"] else row_game[\"away\"]\n            tc=get_team(ctx,team or \"\"); oc=get_team(ctx,opp or \"\")\n            proj,sd,notes=player_projection(pr,r.get(\"prop\"),tc,oc,row_game,team or \"\")\n"""
new="""            # The live line feed maps player team_id to this exact matchup, so it\n            # is the strongest current-role identity. Historical player-bank school\n            # remains only the production sample source (important for transfers).\n            live_team=str(r.get('team') or '')\n            team=canonical_prop_team({**r,'team':live_team},row_game,pr)\n            if team not in {row_game['away'],row_game['home']}:\n                team=''\n                for t in [row_game['away'],row_game['home']]:\n                    a,b=norm_name(live_team),norm_name(t)\n                    if a and (a==b or a in b or b in a): team=t; break\n            opp=row_game[\"home\"] if team==row_game[\"away\"] else row_game[\"away\"]\n            tc=get_team(ctx,team or \"\"); oc=get_team(ctx,opp or \"\")\n            model_pr=dict(pr)\n            if team: model_pr['current_team']=team\n            proj,sd,notes=player_projection(model_pr,r.get(\"prop\"),tc,oc,row_game,team or \"\")\n"""
if old not in s: raise SystemExit('app live-team block marker missing')
s=s.replace(old,new,1)
# Reliability uses the current-team aware player record and marks transfers.
old="""            src=str(pr.get(\"sample_source\") or \"fallback\").lower(); gp=sf(pr.get(\"games\"),0)\n            if src==\"current\": pcap=.72 if gp<=1 else (.80 if gp<=3 else .88)\n            elif src==\"prior\": pcap=.76 if gp>=8 else .70\n            else: pcap=.66\n            p=min(max(p,1-pcap),pcap)\n"""
new="""            src=str(model_pr.get(\"sample_source\") or \"fallback\").lower(); gp=sf(model_pr.get(\"games\"),0)\n            hist_team=str(model_pr.get('team') or ''); current_team=str(model_pr.get('current_team') or '')\n            transferred=bool(src=='prior' and hist_team and current_team and norm_name(hist_team)!=norm_name(current_team))\n            if src==\"current\": pcap=.72 if gp<=1 else (.80 if gp<=3 else .88)\n            elif src==\"prior\": pcap=.70 if gp>=8 else .66\n            else: pcap=.64\n            if transferred: pcap=min(pcap,.66); notes.append('transfer/current-role uncertainty cap')\n            if not team: pcap=min(pcap,.56); notes.append('current team unresolved')\n            p=min(max(p,1-pcap),pcap)\n"""
if old not in s: raise SystemExit('probability calibration marker missing')
s=s.replace(old,new,1)
s=s.replace('CFB Prop Engine v2.3 — NFL-STYLE FINAL + CURRENT ROSTER OPPORTUNITY','CFB Prop Engine v2.4 — NFL-STYLE LIVE TEAM + OPPORTUNITY LOCK')
p.write_text(s)
print('v2.4 live-team opportunity patch applied')
