from pathlib import Path
p=Path('app.py'); s=p.read_text()
if 'from free_data import load_free_stack' not in s:
    s=s.replace('import streamlit as st','import streamlit as st\nfrom free_data import load_free_stack',1)
s=s.replace('APP_VERSION = "CFB Prop Engine v1.2 — ELITE PLAYER CARDS + CFB DATA STACK"','APP_VERSION = "CFB Prop Engine v1.3 — FREE DATA + ELITE PLAYER CARDS"')
s=s.replace('CFBD + Odds API + Open-Meteo ready','FREE SportsDataverse + NCAA + Open-Meteo · paid APIs optional')
old='''with st.sidebar:\n    st.header("CFB Controls")\n    st.write("CFBD", "✅" if cfbd.ready else "❌ add CFBD_API_KEY")\n    st.write("Odds", "✅" if odds.ready else "⚪ optional ODDS_API_KEY")\n    force=st.button("🔄 Refresh CFB Data",use_container_width=True,type="primary")\n    st.caption("API keys stay server-side in Railway/GitHub secrets. The model never hardcodes a sportsbook line as truth.")\n\nwith st.spinner("Loading CFB data…"):\n    bundle=load_bundle(cfbd,int(year),int(week),force=force) if cfbd.ready else {"games":[],"core":[],"sp":[],"srs":[],"elo":[],"rankings":[],"talent":[],"player_stats":[],"advanced":[],"errors":{}}\nctx=build_team_context(bundle)\ngp=team_games_played(bundle.get("games",[]),int(week))\nplayers=parse_player_stats(bundle.get("player_stats",[]),gp)\ninjuries_df=load_optional_csv("injuries.csv")\ndepth_df=load_optional_csv("depth_chart.csv")\ngame_context_df=load_optional_csv("game_context.csv")\ntry: game_odds=odds.game_odds(force=force) if odds.ready else []\nexcept Exception as e: game_odds=[]; bundle.setdefault("errors",{})["odds"]=str(e)\nmarket_map=implied_market(game_odds)'''
new='''with st.sidebar:\n    st.header("CFB Controls")\n    st.write("Free CFB data", "✅ SportsDataverse + NCAA")\n    st.write("CFBD paid API", "✅ optional" if cfbd.ready else "⚪ not needed")\n    st.write("Odds paid API", "✅ optional" if odds.ready else "⚪ not needed — enter player lines manually")\n    force=st.button("🔄 Refresh CFB Data",use_container_width=True,type="primary")\n    st.caption("No paid key is required. SportsDataverse supplies schedules/player/team/advanced/FPI data; NCAA supplies ranking fallback. Paid APIs remain optional only.")\n\nwith st.spinner("Loading FREE CFB data…"):\n    if cfbd.ready:\n        bundle=load_bundle(cfbd,int(year),int(week),force=force)\n        ctx=build_team_context(bundle)\n        gp=team_games_played(bundle.get("games",[]),int(week))\n        players=parse_player_stats(bundle.get("player_stats",[]),gp)\n        try: game_odds=odds.game_odds(force=force) if odds.ready else []\n        except Exception as e: game_odds=[]; bundle.setdefault("errors",{})["odds"]=str(e)\n        market_map=implied_market(game_odds)\n        data_mode="CFBD API"\n    else:\n        bundle,ctx,players,market_map=load_free_stack(int(year),int(week))\n        data_mode="FREE SportsDataverse/NCAA"\ninjuries_df=load_optional_csv("injuries.csv")\ndepth_df=load_optional_csv("depth_chart.csv")\ngame_context_df=load_optional_csv("game_context.csv")'''
if old not in s: raise SystemExit('loading block not found')
s=s.replace(old,new,1)
s=s.replace('if not cfbd.ready: st.warning("Add CFBD_API_KEY to load the current CFB slate and ratings.")\n    elif not week_games:','if not week_games:')
s=s.replace('source=st.radio("Prop lines",["Live Odds API","Manual"],horizontal=True)','source=st.radio("Prop lines",(["Live Odds API","Manual"] if odds.ready else ["Manual"]),horizontal=True)')
s=s.replace('default_text="Player Name,Team,Passing Yards,275.5,Over\\nPlayer Name,Team,Receiving Yards,69.5,Over"','default_text="Player Name,Team,Passing Yards,275.5,Over\\nPlayer Name,Team,Receiving Yards,69.5,Over"')
s=s.replace('No usable CFBD player season sample for: ','No usable player-season sample for: ')
s=s.replace('st.subheader("Data Readiness")','st.subheader("Data Readiness")\n    st.success(f"Active source: {data_mode}")')
s=s.replace('st.markdown("**Current architecture**")\n    st.code("CFBD → cached raw data → team power/opponent unit context → game environment → player opportunity → prop projection → market line → probability/edge → save/grade",language="text")','st.markdown("**Current architecture**")\n    st.code("SportsDataverse/NCAA (free) → cached parquet/JSON → team power + pass/rush matchup → game environment → player opportunity → projection → manual prop line → probability/edge → save/grade",language="text")')
# In free mode the old CFBD health table is mostly empty; append the free dataset health table.
marker='''    if bundle.get("errors"):\n        st.warning("Some endpoints did not load. The app keeps the rest running and reports them here instead of silently substituting fake data.")\n        st.json(bundle["errors"])'''
repl='''    if bundle.get("free_health"):\n        st.markdown("**Free-source rows loaded**")\n        st.dataframe(pd.DataFrame([{"Dataset":k,"Rows":v,"Ready":v>0} for k,v in bundle["free_health"].items()]),use_container_width=True,hide_index=True)\n    if bundle.get("errors"):\n        st.warning("Some sources did not load. The rest of the app stays live and reports missing layers instead of inventing data.")\n        st.json(bundle["errors"])'''
s=s.replace(marker,repl,1)
p.write_text(s)
